### ISSUE TITLE
even worse

### ISSUE THREAD

**Issue by ramsyiq** [MrFawkes1337/CorsacHats#2]
Closed due to no update, and 1.0.3 is tested working on Local games, Official Servers, AND Impostor Servers.

_Originally posted by @MrFawkes1337 in https://github.com/MrFawkes1337/CorsacHats/issues/1#issuecomment-817593753_

[Message: Preloader] BepInEx 6.0.0-reactor.18 - Among Us
[Message: Preloader] BLEEDING EDGE Build #18 from f7d481dda69a6a4964d41d3558a215049e260077 at reactor
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2020.2.6.9052483
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [CorsacHats 1.3.0]
[Message:CorsacHats] Looking HarmonyLib.HarmonyPatch
[Message:CorsacHats] Is patched? True
[Message:   BepInEx] Chainloader startup complete
[Message:CorsacHats] Adding filesystem hats
[Info   :CorsacHats] Looking for *.hat.png hats in path: E:\SteamGames\steamapps\common\Among Us\CorsacHats
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Bretman.hat.png
[Message:CorsacHats] Creating Hat: Bretman.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Corpse.hat.png
[Message:CorsacHats] Creating Hat: Corpse.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Fawkes.hat.png
[Message:CorsacHats] Creating Hat: Fawkes.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Fawkes2.hat.png
[Message:CorsacHats] Creating Hat: Fawkes2.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Fawkes9.hat.png
[Message:CorsacHats] Creating Hat: Fawkes9.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\nyx.hat.png
[Message:CorsacHats] Creating Hat: nyx.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Poki.hat.png
[Message:CorsacHats] Creating Hat: Poki.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Rum.hat.png
[Message:CorsacHats] Creating Hat: Rum.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Sykkunno.hat.png
[Message:CorsacHats] Creating Hat: Sykkunno.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Sykunno.hat.png
[Message:CorsacHats] Creating Hat: Sykunno.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Taylor.hat.png
[Message:CorsacHats] Creating Hat: Taylor.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\toast.hat.png
[Message:CorsacHats] Creating Hat: toast.hat
[Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Vegeta.hat.png
[Message:CorsacHats] Creating Hat: Vegeta.hat

I don't even have E:/ drive

**Comment by ramsyiq** [comment]
> Closed due to no update, and 1.0.3 is tested working on Local games, Official Servers, AND Impostor Servers.
> 
> _Originally posted by @MrFawkes1337 in [#1 (comment)](https://github.com/MrFawkes1337/CorsacHats/issues/1#issuecomment-817593753)_
> 
> [Message: Preloader] BepInEx 6.0.0-reactor.18 - Among Us
> [Message: Preloader] BLEEDING EDGE Build #18 from f7d481dda69a6a4964d41d3558a215049e260077 at reactor
> [Info : BepInEx] System platform: Bits64, Windows
> [Info : Preloader] Running under Unity v2020.2.6.9052483
> [Info : Preloader] 0 patcher plugins loaded
> [Info : Preloader] 0 assemblies discovered
> [Message: BepInEx] Chainloader initialized
> [Info :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
> [Info : BepInEx] 1 plugin to load
> [Info : BepInEx] Loading [CorsacHats 1.3.0]
> [Message:CorsacHats] Looking HarmonyLib.HarmonyPatch
> [Message:CorsacHats] Is patched? True
> [Message: BepInEx] Chainloader startup complete
> [Message:CorsacHats] Adding filesystem hats
> [Info :CorsacHats] Looking for *.hat.png hats in path: E:\SteamGames\steamapps\common\Among Us\CorsacHats
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Bretman.hat.png
> [Message:CorsacHats] Creating Hat: Bretman.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Corpse.hat.png
> [Message:CorsacHats] Creating Hat: Corpse.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Fawkes.hat.png
> [Message:CorsacHats] Creating Hat: Fawkes.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Fawkes2.hat.png
> [Message:CorsacHats] Creating Hat: Fawkes2.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Fawkes9.hat.png
> [Message:CorsacHats] Creating Hat: Fawkes9.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\nyx.hat.png
> [Message:CorsacHats] Creating Hat: nyx.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Poki.hat.png
> [Message:CorsacHats] Creating Hat: Poki.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Rum.hat.png
> [Message:CorsacHats] Creating Hat: Rum.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Sykkunno.hat.png
> [Message:CorsacHats] Creating Hat: Sykkunno.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Sykunno.hat.png
> [Message:CorsacHats] Creating Hat: Sykunno.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Taylor.hat.png
> [Message:CorsacHats] Creating Hat: Taylor.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\toast.hat.png
> [Message:CorsacHats] Creating Hat: toast.hat
> [Message:CorsacHats] Reaching Filesystem Hat: E:\SteamGames\steamapps\common\Among Us\CorsacHats\Vegeta.hat.png
> [Message:CorsacHats] Creating Hat: Vegeta.hat
> 
> I don't even have E:/ drive

and I updated to the latest release.. not sure why log said its 1.0.0

**Comment by MrFawkes1337** [comment]
Delete ALL logs currently in that folder, THEN get a Clean Log, and post it. I seem to have inlcuded my own logs as thats one of mine.

**Comment by MrFawkes1337** [comment]
Can this be closed? Did the update work for you?

**Comment by ramsyiq** [comment]
[Message: Preloader] BepInEx 6.0.0-reactor.18 - Among Us
[Message: Preloader] BLEEDING EDGE Build #18 from f7d481dda69a6a4964d41d3558a215049e260077 at reactor
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2020.2.6.9052483
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [UnityExplorer 3.3.12]
[Info   :Unhollower] Registered mono type UnityExplorer.ExplorerBepInPlugin+ExplorerBehaviour in il2cpp domain
[Message:UnityExplorer] ExplorerBehaviour.Awake
[Message:UnityExplorer] Initializing Legacy Input support...
[Message:UnityExplorer] Exception setting up Harmony patches:
HarmonyLib.HarmonyException: IL Compile Error (unknown location)
[Message:UnityExplorer] UnityExplorer 3.3.12 initialized.
[Info   :   BepInEx] Loading [CorsacHats 1.1.0]
[Message:CorsacHats] Patching harmony...
[Message:CorsacHats] Looking HarmonyLib.HarmonyPatch
[Message:CorsacHats] Is patched? True
[Message:   BepInEx] Chainloader startup complete
[Message:UnityExplorer] Creating UI, after delay of 1 second(s).
[Message:UnityExplorer] This game does not ship with the 'UI/Default' shader, using manual Default Shader...
[Message:UnityExplorer] Loaded UI AssetBundle
[Message:UnityExplorer] UI initialized.
[Message:CorsacHats] Prefix running.
[Message:CorsacHats] Adding filesystem hats
[Info   :CorsacHats] Looking for *.hat.png hats in path: C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats
[Warning:CorsacHats] No Filesystem Hats found, dumping the full list of file names in searched path
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_annamaja.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_annie.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_aphex.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_aplatypuss.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_asexual.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_bal.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_bisexual.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_bloody.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_breeh.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_cheesy.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_chilled.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_corpse.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_dippines.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_dizzilulu.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_draft1.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_dream.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_ellum.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_falcone.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_fime.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_freya.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_gasmask.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_gay.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_harrie.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_hellokitty.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_junkyard.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_kay.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_lexie.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_ludwig.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_megumins.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_nonbinary.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_pansexual.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_poki.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_razz.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_shubble.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_sidesxope.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_siiain.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_slushie.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_stumpy.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_sykkuno.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_toast.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_trans_1.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_trans_2.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_trans_3.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_trans_4.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_valkyrae.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_vikram_1.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_vikram_2.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_ze.png
[Info   :CorsacHats] C:\Program Files (x86)\Steam\steamapps\31.3\Among Us\CorsacHats\hat_zylus.png
[Message:CorsacHats] Postfix running.
[Message:CorsacHats] Finalizer running.
[Message:CorsacHats] Prefix running.
[Message:CorsacHats] Already loaded, skipped
[Message:CorsacHats] Postfix running.
[Message:CorsacHats] Finalizer running.
[Message:CorsacHats] Prefix running.
[Message:CorsacHats] Already loaded, skipped
[Message:CorsacHats] Postfix running.
[Message:CorsacHats] Finalizer running.
[Message:CorsacHats] Prefix running.
[Message:CorsacHats] Already loaded, skipped
[Message:CorsacHats] Postfix running.
[Message:CorsacHats] Finalizer running.
[Message:CorsacHats] Prefix running.
[Message:CorsacHats] Already loaded, skipped
[Message:CorsacHats] Postfix running.
[Message:CorsacHats] Finalizer running.
[Message:CorsacHats] Prefix running.
[Message:CorsacHats] Already loaded, skipped
[Message:CorsacHats] Postfix running.
[Message:CorsacHats] Finalizer running.
[Message:CorsacHats] Prefix running.
[Message:CorsacHats] Already loaded, skipped
[Message:CorsacHats] Postfix running.
[Message:CorsacHats] Finalizer running.
[Message:CorsacHats] Prefix running.
.................................................

It's not working for me.. maybe it's just me so i'm closing this..

**Comment by MrFawkes1337** [comment]
Shoot me a DM on Discord at MrFawkes1337#9394 and I’ll help you, this is confusing as it works for me. You named the hats wrong anyway, it should be Hatname.hat.png.

**Comment by MrFawkes1337** [comment]
You’re also running an outdated release, as 1.1.0 hasn’t been live since the initial update
